"""
net_fetcher.py
Scrapes NCAA NET rankings from the public NCAA website.
No login required  this is public data.
"""

import requests
import pandas as pd
from bs4 import BeautifulSoup


NET_URL = "https://www.ncaa.com/rankings/basketball-men/d1/ncaa-mens-basketball-net-rankings"

# Maps NET team name -> KenPom team name
NET_TO_KENPOM = {
    "Abilene Christian": "Abilene Christian",
    "Air Force": "Air Force",
    "Akron": "Akron",
    "Alabama": "Alabama",
    "Alabama A&M": "Alabama A&M",
    "Alabama St.": "Alabama St.",
    "UAlbany": "Albany",
    "Alcorn": "Alcorn St.",
    "American": "American",
    "App State": "Appalachian St.",
    "Arizona St.": "Arizona St.",
    "Arizona": "Arizona",
    "Arkansas": "Arkansas",
    "Arkansas St.": "Arkansas St.",
    "Ark.-Pine Bluff": "Arkansas Pine Bluff",
    "Army West Point": "Army",
    "Auburn": "Auburn",
    "Austin Peay": "Austin Peay",
    "Ball St.": "Ball St.",
    "Baylor": "Baylor",
    "Bellarmine": "Bellarmine",
    "Belmont": "Belmont",
    "Bethune-Cookman": "Bethune Cookman",
    "Binghamton": "Binghamton",
    "Boise St.": "Boise St.",
    "Boston College": "Boston College",
    "Boston U.": "Boston University",
    "Bowling Green": "Bowling Green",
    "Bradley": "Bradley",
    "Brown": "Brown",
    "Bryant": "Bryant",
    "Bucknell": "Bucknell",
    "Buffalo": "Buffalo",
    "Butler": "Butler",
    "BYU": "BYU",
    "Cal Poly": "Cal Poly",
    "CSU Bakersfield": "Cal St. Bakersfield",
    "Cal St. Fullerton": "Cal St. Fullerton",
    "CSUN": "CSUN",
    "California Baptist": "Cal Baptist",
    "California": "California",
    "Campbell": "Campbell",
    "Canisius": "Canisius",
    "Central Ark.": "Central Arkansas",
    "Central Conn. St.": "Central Connecticut",
    "Central Mich.": "Central Michigan",
    "Col. of Charleston": "Charleston",
    "Charleston So.": "Charleston Southern",
    "Charlotte": "Charlotte",
    "Chattanooga": "Chattanooga",
    "Chicago St.": "Chicago St.",
    "Cincinnati": "Cincinnati",
    "Clemson": "Clemson",
    "Cleveland St.": "Cleveland St.",
    "Coastal Carolina": "Coastal Carolina",
    "Colgate": "Colgate",
    "Colorado": "Colorado",
    "Colorado St.": "Colorado St.",
    "Columbia": "Columbia",
    "Coppin St.": "Coppin St.",
    "Cornell": "Cornell",
    "Creighton": "Creighton",
    "Dartmouth": "Dartmouth",
    "Davidson": "Davidson",
    "Dayton": "Dayton",
    "Delaware": "Delaware",
    "Delaware St.": "Delaware St.",
    "Denver": "Denver",
    "DePaul": "DePaul",
    "Detroit Mercy": "Detroit Mercy",
    "Drake": "Drake",
    "Drexel": "Drexel",
    "Duke": "Duke",
    "Duquesne": "Duquesne",
    "East Carolina": "East Carolina",
    "ETSU": "East Tennessee St.",
    "Eastern Ill.": "Eastern Illinois",
    "Eastern Ky.": "Eastern Kentucky",
    "Eastern Mich.": "Eastern Michigan",
    "Eastern Wash.": "Eastern Washington",
    "Elon": "Elon",
    "Evansville": "Evansville",
    "Fairfield": "Fairfield",
    "FDU": "Fairleigh Dickinson",
    "Florida A&M": "Florida A&M",
    "Fla. Atlantic": "Florida Atlantic",
    "Florida": "Florida",
    "FGCU": "Florida Gulf Coast",
    "FIU": "FIU",
    "Florida St.": "Florida St.",
    "Fordham": "Fordham",
    "Fresno St.": "Fresno St.",
    "Furman": "Furman",
    "Gardner-Webb": "Gardner Webb",
    "George Mason": "George Mason",
    "George Washington": "George Washington",
    "Georgetown": "Georgetown",
    "Georgia": "Georgia",
    "Ga. Southern": "Georgia Southern",
    "Georgia St.": "Georgia St.",
    "Georgia Tech": "Georgia Tech",
    "Gonzaga": "Gonzaga",
    "Grambling": "Grambling St.",
    "Grand Canyon": "Grand Canyon",
    "Green Bay": "Green Bay",
    "Hampton": "Hampton",
    "Harvard": "Harvard",
    "Hawaii": "Hawaii",
    "High Point": "High Point",
    "Hofstra": "Hofstra",
    "Holy Cross": "Holy Cross",
    "Houston Christian": "Houston Christian",
    "Houston": "Houston",
    "Howard": "Howard",
    "Idaho": "Idaho St.",
    "Idaho St.": "Idaho",
    "Illinois": "Illinois",
    "Illinois St.": "Illinois St.",
    "UIW": "Incarnate Word",
    "Indiana": "Indiana",
    "Indiana St.": "Indiana St.",
    "Iona": "Iona",
    "Iowa": "Iowa",
    "Iowa St.": "Iowa St.",
    "Jackson St.": "Jackson St.",
    "Jacksonville": "Jacksonville",
    "Jacksonville St.": "Jacksonville St.",
    "James Madison": "James Madison",
    "Kansas City": "UMKC",
    "Kansas": "Kansas",
    "Kansas St.": "Kansas St.",
    "Kennesaw St.": "Kennesaw St.",
    "Kent St.": "Kent St.",
    "Kentucky": "Kentucky",
    "La Salle": "La Salle",
    "Lafayette": "Lafayette",
    "Lamar University": "Lamar",
    "Lehigh": "Lehigh",
    "Liberty": "Liberty",
    "Lindenwood": "Lindenwood",
    "Lipscomb": "Lipscomb",
    "Little Rock": "Little Rock",
    "Long Beach St.": "Long Beach St.",
    "LIU": "LIU",
    "Longwood": "Longwood",
    "Louisiana": "Louisiana",
    "Louisiana Tech": "Louisiana Tech",
    "Louisville": "Louisville",
    "Loyola Chicago": "Loyola Chicago",
    "Loyola Maryland": "Loyola MD",
    "LMU (CA)": "Loyola Marymount",
    "LSU": "LSU",
    "Maine": "Maine",
    "Manhattan": "Manhattan",
    "Marist": "Marist",
    "Marquette": "Marquette",
    "Marshall": "Marshall",
    "Maryland": "Maryland",
    "UMES": "Maryland Eastern Shore",
    "McNeese": "McNeese",
    "Memphis": "Memphis",
    "Mercer": "Mercer",
    "Merrimack": "Merrimack",
    "Miami (OH)": "Miami OH",
    "Miami (FL)": "Miami FL",
    "Michigan St.": "Michigan St.",
    "Michigan": "Michigan",
    "Middle Tenn.": "Middle Tennessee",
    "Milwaukee": "Milwaukee",
    "Minnesota": "Minnesota",
    "Mississippi St.": "Mississippi St.",
    "Mississippi Val.": "Mississippi Valley St.",
    "Missouri St.": "Missouri St.",
    "Missouri": "Missouri",
    "Monmouth": "Monmouth",
    "Montana": "Montana",
    "Montana St.": "Montana St.",
    "Morehead St.": "Morehead St.",
    "Morgan St.": "Morgan St.",
    "Mount St. Mary's": "Mount St. Mary's",
    "Murray St.": "Murray St.",
    "Navy": "Navy",
    "NC State": "N.C. State",
    "Nebraska": "Nebraska",
    "Nevada": "Nevada",
    "New Hampshire": "New Hampshire",
    "New Mexico": "New Mexico",
    "New Mexico St.": "New Mexico St.",
    "New Orleans": "New Orleans",
    "Niagara": "Niagara",
    "Nicholls": "Nicholls",
    "NJIT": "NJIT",
    "Norfolk St.": "Norfolk St.",
    "North Ala.": "North Alabama",
    "N.C. A&T": "North Carolina A&T",
    "N.C. Central": "North Carolina Central",
    "North Carolina": "North Carolina",
    "North Dakota": "North Dakota",
    "North Dakota St.": "North Dakota St.",
    "North Florida": "North Florida",
    "North Texas": "North Texas",
    "Northeastern": "Northeastern",
    "Northern Ariz.": "Northern Arizona",
    "Northern Colo.": "Northern Colorado",
    "NIU": "Northern Illinois",
    "UNI": "Northern Iowa",
    "Northern Ky.": "Northern Kentucky",
    "Northwestern St.": "Northwestern St.",
    "Northwestern": "Northwestern",
    "Notre Dame": "Notre Dame",
    "Oakland": "Oakland",
    "Ohio": "Ohio",
    "Ohio St.": "Ohio St.",
    "Oklahoma": "Oklahoma",
    "Oklahoma St.": "Oklahoma St.",
    "Old Dominion": "Old Dominion",
    "Ole Miss": "Mississippi",
    "Omaha": "Nebraska Omaha",
    "Oral Roberts": "Oral Roberts",
    "Oregon": "Oregon",
    "Oregon St.": "Oregon St.",
    "Pacific": "Pacific",
    "Penn St.": "Penn St.",
    "Penn": "Penn",
    "Pepperdine": "Pepperdine",
    "Pittsburgh": "Pittsburgh",
    "Portland": "Portland",
    "Portland St.": "Portland St.",
    "Prairie View": "Prairie View A&M",
    "Presbyterian": "Presbyterian",
    "Princeton": "Princeton",
    "Providence": "Providence",
    "Purdue": "Purdue",
    "Purdue Fort Wayne": "Purdue Fort Wayne",
    "Queens (NC)": "Queens",
    "Quinnipiac": "Quinnipiac",
    "Radford": "Radford",
    "Rhode Island": "Rhode Island",
    "Rice": "Rice",
    "Richmond": "Richmond",
    "Rider": "Rider",
    "Robert Morris": "Robert Morris",
    "Rutgers": "Rutgers",
    "Sacramento St.": "Sacramento St.",
    "Sacred Heart": "Sacred Heart",
    "Saint Joseph's": "Saint Joseph's",
    "Saint Louis": "Saint Louis",
    "Saint Mary's (CA)": "Saint Mary's",
    "Saint Peter's": "Saint Peter's",
    "Sam Houston": "Sam Houston St.",
    "Samford": "Samford",
    "San Diego St.": "San Diego St.",
    "San Diego": "San Diego",
    "San Francisco": "San Francisco",
    "San Jose St.": "San Jose St.",
    "Santa Clara": "Santa Clara",
    "Southeastern La.": "Southeastern Louisiana",
    "Seattle U": "Seattle",
    "Seton Hall": "Seton Hall",
    "Siena": "Siena",
    "SIUE": "SIUE",
    "SMU": "SMU",
    "South Alabama": "South Alabama",
    "South Carolina": "South Carolina",
    "South Carolina St.": "South Carolina St.",
    "USC Upstate": "USC Upstate",
    "South Dakota": "South Dakota",
    "South Dakota St.": "South Dakota St.",
    "South Fla.": "South Florida",
    "Southeast Mo. St.": "Southeast Missouri",
    "Southern Ill.": "Southern Illinois",
    "Southern Ind.": "Southern Indiana",
    "Southern U.": "Southern",
    "Southern Miss.": "Southern Miss",
    "Southern Utah": "Southern Utah",
    "St. Bonaventure": "St. Bonaventure",
    "Saint Francis": "Saint Francis",
    "St. John's (NY)": "St. John's",
    "St. Thomas (MN)": "St. Thomas",
    "Stanford": "Stanford",
    "SFA": "Stephen F. Austin",
    "Stetson": "Stetson",
    "Stonehill": "Stonehill",
    "Stony Brook": "Stony Brook",
    "Syracuse": "Syracuse",
    "Tarleton St.": "Tarleton St.",
    "TCU": "TCU",
    "Temple": "Temple",
    "Tennessee St.": "Tennessee St.",
    "Tennessee Tech": "Tennessee Tech",
    "Tennessee": "Tennessee",
    "Texas A&M": "Texas A&M",
    "East Texas A&M": "East Texas A&M",
    "A&M-Corpus Christi": "Texas A&M Corpus Chris",
    "Texas": "Texas",
    "Texas Southern": "Texas Southern",
    "Texas St.": "Texas St.",
    "Texas Tech": "Texas Tech",
    "The Citadel": "The Citadel",
    "Toledo": "Toledo",
    "Towson": "Towson",
    "Troy": "Troy",
    "Tulane": "Tulane",
    "Tulsa": "Tulsa",
    "UAB": "UAB",
    "UC Davis": "UC Davis",
    "UC Irvine": "UC Irvine",
    "UC Riverside": "UC Riverside",
    "UC San Diego": "UC San Diego",
    "UC Santa Barbara": "UC Santa Barbara",
    "UCF": "UCF",
    "UCLA": "UCLA",
    "UConn": "Connecticut",
    "UIC": "Illinois Chicago",
    "ULM": "Louisiana Monroe",
    "UMass Lowell": "UMass Lowell",
    "Massachusetts": "Massachusetts",
    "UMBC": "UMBC",
    "UNC Asheville": "UNC Asheville",
    "UNC Greensboro": "UNC Greensboro",
    "UNCW": "UNC Wilmington",
    "UNLV": "UNLV",
    "Southern California": "USC",
    "UT Arlington": "UT Arlington",
    "UT Martin": "Tennessee Martin",
    "UTRGV": "UT Rio Grande Valley",
    "Utah St.": "Utah St.",
    "Utah Tech": "Utah Tech",
    "Utah": "Utah",
    "Utah Valley": "Utah Valley",
    "UTEP": "UTEP",
    "UTSA": "UTSA",
    "Valparaiso": "Valparaiso",
    "Vanderbilt": "Vanderbilt",
    "VCU": "VCU",
    "Vermont": "Vermont",
    "Villanova": "Villanova",
    "Virginia": "Virginia",
    "Virginia Tech": "Virginia Tech",
    "VMI": "VMI",
    "Wagner": "Wagner",
    "Wake Forest": "Wake Forest",
    "Washington": "Washington",
    "Washington St.": "Washington St.",
    "Weber St.": "Weber St.",
    "West Virginia": "West Virginia",
    "Western Caro.": "Western Carolina",
    "Western Ill.": "Western Illinois",
    "Western Ky.": "Western Kentucky",
    "Western Mich.": "Western Michigan",
    "Wichita St.": "Wichita St.",
    "William & Mary": "William & Mary",
    "Winthrop": "Winthrop",
    "Wisconsin": "Wisconsin",
    "Wofford": "Wofford",
    "Wright St.": "Wright St.",
    "Wyoming": "Wyoming",
    "Xavier": "Xavier",
    "Yale": "Yale",
    "Youngstown St.": "Youngstown St.",
    "Le Moyne": "Le Moyne",
    "Mercyhurst": "Mercyhurst",
    "New Haven": "New Haven",
    "West Georgia": "West Georgia",
}


def fetch_net_rankings() -> pd.DataFrame:
    """Scrape NCAA NET rankings and return as a DataFrame."""
    headers = {"User-Agent": "Mozilla/5.0"}
    resp = requests.get(NET_URL, headers=headers)
    resp.raise_for_status()

    soup = BeautifulSoup(resp.text, "html.parser")
    table = soup.find("table")

    if table is None:
        raise RuntimeError("Could not find rankings table on NCAA page. Structure may have changed.")

    rows = []
    headers_row = [th.text.strip() for th in table.find("tr").find_all("th")]

    for tr in table.find_all("tr")[1:]:
        cells = [td.text.strip() for td in tr.find_all("td")]
        if cells:
            rows.append(cells)

    df = pd.DataFrame(rows, columns=headers_row)

    # Normalize column names
    df.columns = [c.strip().replace(" ", "_") for c in df.columns]

    # Try to standardize rank and team name columns
    for col in df.columns:
        if "rank" in col.lower():
            df.rename(columns={col: "Rank"}, inplace=True)
            break
    for col in df.columns:
        if "team" in col.lower() or "school" in col.lower():
            df.rename(columns={col: "TeamName"}, inplace=True)
            break

    df["Rank"] = pd.to_numeric(df["Rank"], errors="coerce")
    df.dropna(subset=["Rank"], inplace=True)

    # Apply name mapping: NET name -> KenPom name
    df["TeamName"] = df["TeamName"].map(NET_TO_KENPOM).fillna(df["TeamName"])

    return df


if __name__ == "__main__":
    df = fetch_net_rankings()
    df.to_csv("data/net.csv", index=False)
    print(f" Saved NET rankings: {len(df)} teams")
    print(df.head())
